const CONSTANTS = {
  FETCH_PLAYLIST_ITEMS_REQUEST: 'FETCH_PLAYLIST_ITEMS_REQUEST',
  FETCH_PLAYLIST_ITEMS_SUCCESS: 'FETCH_PLAYLIST_ITEMS_SUCCESS',
  FETCH_PLAYLIST_ITEMS_FAILURE: 'FETCH_PLAYLIST_ITEMS_FAILURE',

  FETCH_VIDEO_REQUEST: 'FETCH_VIDEO_REQUEST',
  FETCH_VIDEO_SUCCESS: 'FETCH_VIDEO_SUCCESS',
  FETCH_VIDEO_FAILURE: 'FETCH_VIDEO_FAILURE',

  FETCH_CATEGORY_VIDEOS_REQUEST: 'FETCH_CATEGORY_VIDEOS_REQUEST',
  FETCH_CATEGORY_VIDEOS_SUCCESS: 'FETCH_CATEGORY_VIDEOS_SUCCESS',
  FETCH_CATEGORY_VIDEOS_FAILURE: 'FETCH_CATEGORY_VIDEOS_FAILURE',

  FETCH_CHANNEL_REQUEST: 'FETCH_CHANNEL_REQUEST',
  FETCH_CHANNEL_SUCCESS: 'FETCH_CHANNEL_SUCCESS',
  FETCH_CHANNEL_FAILURE: 'FETCH_CHANNEL_FAILURE',
};

export default CONSTANTS;
